$skillPath = Split-Path -Parent $PSScriptRoot
$scriptPath = $MyInvocation.MyCommand.Path
$outFile = "$PSScriptRoot\ps-output.txt"
$fileExists = Test-Path $outFile

$content = @"
========================================
Generated by: SubAgent2 (subag2print-executor)
========================================
Skill Location: $skillPath
Script Executed: $scriptPath
Model: opencode/big-pickle
Permissions: bash=allow, edit=deny, write=allow
Timestamp: $(Get-Date)
========================================
Hello from SubAgent2 - file created successfully!
========================================
"@

if ($fileExists) {
    Add-Content -Path $outFile -Value "`n--- APPENDED ---`n$content"
    Write-Output "----- File Appended: $outFile -----"
} else {
    Set-Content -Path $outFile -Value $content
    Write-Output "----- File Created: $outFile -----"
}
Get-Content -Path $outFile

# Open CMD window to display file content
Start-Process -FilePath "cmd.exe" -ArgumentList "/k", "type `"$outFile`""
